# -*- coding: utf-8 -*-
"""Time/Space Complexity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176AnXq8LuaLE_j66YYeLU9sPhSJnVmCj
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# n = 50000
# numbers = [i+1 for i in range(n) ]
# 
# counter = 0
# 
# for i in range(n):
#     x = 1
# 
#     if x in numbers:
#         counter += 1
# 
# print(counter)
#

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# n = 50000
# numbers = [i+1 for i in range(n) ]
# 
# counter = 0
# 
# for i in range(n):
#     x = n
# 
#     if x in numbers:
#         counter += 1
# 
# print(counter)
#